services:
  #database
  mysql:
    image: mysql:8.4

    container_name: mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: parham86sa

    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      default:

  #user service
  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile.yaml
    container_name: user-service

    restart: always

    ports:
      - "8080:8080"

    depends_on:
      - mysql
  #ride service
  ride-service:
    build:
      context: ./services/ride-service
      dockerfile: Dockerfile.yaml
    container_name: ride-service

    restart: always

    ports:
      - "8081:8081"

    depends_on:
      - mysql
      - user-service
  #payment service
  payment-service:
    build:
      context: ./services/payment-service
      dockerfile: Dockerfile.yaml
    container_name: payment-service

    restart: always

    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - ride-service
      - user-service

volumes:
  mysql-data: